name: hello-world

on: 
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "write something"
        required: false

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - name: make script executable
        run: |
          chmod +x script.sh
          ls -l script.sh
      - name: run script
        run: ./script.sh
