name: hello-world

on: 
  workflow_dispatch:
    inputs:
      apply_for_prod:
        type: boolean
        description: "Tag for ptod/nonprod"
        default: false
      environment:
        type: boolean
        description: "Env"
        required: true

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
